import pyproj

# TODO: Pandas is quite good at working with categorical data. Refactor everything to make use of that.
# It will not only be more readable but will also bring a speedup!

CH1903 = "epsg:21781"
LV05 = CH1903
CH1903_PLUS = "epsg:2056"
LV95 = CH1903_PLUS
WGS84 = "epsg:4326"

MAXIMUM_HOUSEHOLD_SIZE = 12
MINIMUM_AGE_PER_HOUSEHOLD = 16
ACTIVE_AGE = 60

MARITAL_STATUS_SINGLE = 0
MARITAL_STATUS_MARRIED = 1
MARITAL_STATUS_SEPARATE = 2

SEPARATE_SINGLE_THRESHOLD = 45

AGE_CLASS_UPPER_BOUNDS = [6, 15, 18, 24, 30, 45, 65, 80]

CAR_AVAILABILITY_ALWAYS = 0
CAR_AVAILABILITY_SOMETIMES = 1
CAR_AVAILABILITY_NEVER = 2

SEX_MALE = 0
SEX_FEMALE = 1

BIKE_AVAILABILITY_FOR_ALL = 2
BIKE_AVAILABILITY_FOR_SOME = 1
BIKE_AVAILABILITY_FOR_NONE = 0

MZ_AGE_THRESHOLD = 6

INCOME_CLASSES = 9

MAX_NUMBER_OF_CARS_CLASS = 3

POPULATION_DENSITY_RADIUS = 2.5 * 1e3

BASE_SCALING_YEAR = 2015
BASE_PROJECTED_YEAR = 2018
